[package]
name = "methylsim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
rand = "0.8"
rand_distr = "0.4"
tempfile = "3.10"
shell-words = "1.1"
